name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Format
        uses: psf/black@stable
        with:
          options: "--check --diff"
          src: "./src"
          use_pyproject: true
